<div class="top-bar">
    <nav class="top-bar-left">
        <div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="large">
            <button class="menu-toggle" type="button" data-toggle="offCanvas" aria-label="<?php echo $this->translate('Menu'); ?>"><i class="fas fa-bars"></i></button>
         <a href="<?php echo $site->url(); ?>"><img src="/themes/foundation_archiviomemoria/asset/img/logo_ecomuseo_scritta.png" title="Logo Ecomuseo della Valle dei Laghi" id="logosmallscreen"></a>  
        </div>
        <h1><a href="/s/archivio" class="site-title" style="color:#B7410E;font-size:0.6em;">Archivio della Memoria della Valle dei Laghi</a></h1>
    </nav>
    <div class="top-bar-right" id="responsive-menu">
        <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'dropdown']); ?>

        <div class="search">
       <?php echo $this->partial('common/search-form'); ?>
        </div>
<a href="<?php echo $site->url(); ?>"><img src="/themes/foundation_archiviomemoria/asset/img/logo_ecomuseo_scritta.png" title="Logo Ecomuseo della Valle dei Laghi" style="margin-left:10px;margin-right:10px;max-width:250px;"></a>
        
    </div>
</div>
