<!-- 
exception
-->

<?php $itemIdCheck = $item->id()?>

<? if ($itemIdCheck == 4850 or $itemIdCheck == 4879 or $itemIdCheck == 4896 or $itemIdCheck == 4902 or $itemIdCheck == 4905 or $itemIdCheck == 4899 or $itemIdCheck == 4901 or $itemIdCheck == 4900 or $itemIdCheck == 4879 or $itemIdCheck == 4903 or $itemIdCheck == 5854 or $itemIdCheck == 6012): ?>
<style type="text/css">

.resource.show #resource-values {
width: 100%;
}

.resource.show .values .resource-link:hover {
    transform: scale(1.2);
    display:inline-block;
}
.resource.show .values .resource-link {
    transition: transform .2s ease-out;
    display:inline-block;
    text-align: center;
}

   .resource.show .values .resource-link img {
        width: 300px !important;
        height: auto;
    }

    .media-embeds img {
        width: 400px !important;
        height: auto;
    }


     .item_sets {
         display:inline-block;
         width: 320px;
         padding: 20px;
     }

     h4 {
         display: none;
     }

     .media-embeds {
          display:none;
     }

#content > .property {
    display: none;
}

#content > .property ~ .property {
    display: block;
}

.uv {
  font-size: 16px;
}
</style>
 
<? else: ?>
<style type="text/css">
.uv {
  font-size: 16px;
}
</style>

<? endif; ?>

<!-- 
end of exception
-->



<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
?>

<div class="resource-title">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>

<div class="grid-x">

<?php if ($embedMedia && $itemMedia): ?>
<div class="media-embeds">
<?php foreach ($itemMedia as $media):
    echo $media->render();
    //  Ecomuseo Custom start 
    if (sizeof($media->values())>1 || sizeof($itemMedia)>1):
    echo $media->displayValues();
    endif;
    //  Ecomuseo Custom end 
     
endforeach;
?>
</div>
<?php endif; ?>
<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<div id="resource-values" class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $item->displayValues(); ?>
    <?php $itemSets = $item->itemSets(); ?>
    <dl>
    <?php if (count($itemSets) > 0): ?>
    <div class="property">
        <dt><?php echo $translate('Item sets'); ?></dt>
        <div class="values">
            <?php foreach ($itemSets as $itemSet): ?>
            <dd class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></dd>
            <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>
    </dl>

	<dl>
	<?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>
		<div class="property">
    		<dt><?php echo $translate('Site pages'); ?></dt>
    		<div class="values">
        		<?php foreach ($sitePages as $sitePage): ?>
        		<dd class="value"><?php echo $sitePage->link($sitePage->title()); ?></dd>
        		<?php endforeach; ?>
    		</div>
		</div>
	<?php endif; ?>
	</dl>

    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>
</div>

</div>
