<?php
$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>

<div class="resource-title">
<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
<h3 class="label"><?php echo $translate('Media'); ?></h3>
</div>
<?php $this->trigger('view.show.before'); ?>
<?php echo $media->render(); ?>
<?php echo $media->displayValues(); ?>
<?php $this->trigger('view.show.after'); ?>

<?php $itemTitle = $media->item()->title();?>
<b>Per maggior contesto e dettagli su questo materiale, fai riferimento al contenuto a cui si riferisce</b>: <br /><b>→ <?php echo $media->item()->link($itemTitle); ?></b>
